version: 0.1
component: build
timeoutInSeconds: 10000
runAs: root
shell: bash      

steps:
  - type: Command
    timeoutInSeconds: 1200
    name: "Zap Scan"
    command: |
      docker pull owasp/zap2docker-stable:2.11.1
      docker run -v $(pwd):/zap/wrk/:rw --user root owasp/zap2docker-stable:2.11.1 zap-baseline.py -t https://129.158.218.116 -g gen.conf -d -r report.html
outputArtifacts:
  - name: zap-report
    type: BINARY 
    location: report.html
